### ISSUE TITLE
Download fails

### ISSUE THREAD

**Issue by ohadle** [DilumAluthge/OfflineRegistry#28]
Running `julia make.jl` on a mediocre internet connection, I got:

`ERROR: LoadError: failed to clone from https://github.com/MikeInnes/Requires.jl.git, error: GitError(Code:ERROR, Class:Net, curl error: Could not resolve host: github.com`

This happened with different repos on different retries.
Assuming this is due to some connection failure, would resuming an existing download or at least retrying be possible?

**Comment by DilumAluthge** [comment]
Yeah I can add some code to retry a clone if it fails. I’ll ping you once I’ve implemented it.

**Comment by DilumAluthge** [comment]
@ohadle I've merged some changes into master that retry downloads when they fail.

Can you update to the latest master and try it out?

**Comment by DilumAluthge** [comment]
@ohadle Did the new changes work for you?

**Comment by ohadle** [comment]
Yes, looks like they did, thanks! (Sorry about the delay)
I now have a 166 MB `repos` dir and a 3MB `packages` dir.

I still haven't copied everything over to the secured network (it's quite a hassle) or figured out how to set up this registry, that'd be the next step.
