### ISSUE TITLE
How to use this application. 

### ISSUE THREAD

**Issue by alirezamecheng** [DilumAluthge/OfflineRegistry#43]
Hello,
I need to have a mirror repository for many users behind a firewall. My users can't connect to the internet. But I have a system that is connected to the internet and can get the Julia packages and act as a mirror repository for the Julia packages (The users can have access to this system via network). I saw your program recommended for this task but I don't see any documentation about How to use and setup the application. 
I have some questions:
1- How to setup the mirror repo?
2- How to make other users over the network to see this repo instead of trying to connect to the original Julia GitHub repo 
3- How to maintain the repo and keep it update without interfering with others work and projects.

Any help will be appreciated. 
Thank you for your time and attention.

**Comment by DilumAluthge** [comment]
1. To set up the mirror, run the commands in the Usage section of the [README](https://github.com/DilumAluthge/OfflineRegistry/blob/master/README.md).

2. If a user wants to use this mirror, they need to `include` the `startup.jl` and `default-environment.jl` files. So for example, if you have installed the mirror to `/path/to/desired/location`, then the users need to run:
```julia
include("/path/to/desired/location/OfflineRegistry/startup.jl")
include("/path/to/desired/location/OfflineRegistry/default-environment.jl")
```

3. Currently, there is no way to update the mirror. You need to delete the mirror and then rerun the commands to set up the mirror.

**Comment by DilumAluthge** [comment]
I have updated the [README](https://github.com/DilumAluthge/OfflineRegistry/blob/master/README.md) with some more instructions for setting up and using the mirror.

**Comment by alirezamecheng** [comment]
Thank you very much.

**Comment by alirezamecheng** [comment]
I get this error when using the local repo. Do you know what may be the cause of this error?
``` julia 
add Example
 Resolving package versions...
   Cloning [7876af07-990d-54b4-ab0e-23690620f79a] Example from /home/alireza/PackageRepo/OfflineRegistry/repos/E/Example.jl.git
ERROR: failed to clone from /home/alireza/PackageRepo/OfflineRegistry/repos/E/Example.jl.git, error: GitError(Code:ERROR, Class:Net, unsupported URL protocol)

```

**Comment by alirezamecheng** [comment]
> I get this error when using the local repo. Do you know what may be the cause of this error?
> 
> ```julia
> add Example
>  Resolving package versions...
>    Cloning [7876af07-990d-54b4-ab0e-23690620f79a] Example from /home/alireza/PackageRepo/OfflineRegistry/repos/E/Example.jl.git
> ERROR: failed to clone from /home/alireza/PackageRepo/OfflineRegistry/repos/E/Example.jl.git, error: GitError(Code:ERROR, Class:Net, unsupported URL protocol)
> ```

I found that many packages are not available offline in the repo and the error is the result of that.

**Comment by alirezamecheng** [comment]
Please excuse me for the inconvenience, I found your package perfect for my task. 
My goal is to have all registered packages available in the `https://github.com/JuliaRegistries/General.git` to be available for my users (on a cluster computer
I have some question about usage. 
1. It seems that the program doesn't get all the packages in the `general.git` repo. For example in my case `Example.jl`, `IterativeSolvers.jl` and many other packages are missing. 

2. Why there is a necessity for this package and what are the contents of that? How should I get the `REGISTERY_UUID` when I don't have any specific Julia package?
```Bash
export REGISTRY_NAME="MyAwesomeOfflineRegistry"
export REGISTRY_UUID="e8565a5e-8849-4686-8239-e2115313d19d" # Don't use this UUID; generate your own
```
3- How should I change the `offline.toml`?

4- what are the contents of the `broken.packages.toml` and how should I edit this file?

5- What does the `startup.jl` and default-environment.jl files do? Should I change them for any reason?

Please pardon me for the many numbers of questions and taking your time. Any help will be appreciated. 
Thank you.

**Comment by DilumAluthge** [comment]
1. You need to open the file `offline.toml` and read the instructions to download all packages from the General registry. Basically there will be a “false” that you need to change to “true”.

2. This UUID is for your new registry. It has nothing to do with a package. Generate a new UUID4 (google “generate uuid” for a website that generates UUIDs), and then use that value. Every registry needs to have its own unique UUID.

3. See number 1 above. Basically you will need to open up offline.toml and change a false to a true.

4. You probably won’t need to change it.

5. You don’t need to change those files either. Any user that wants to use your registry will simply include those two files, and then they have access to your registry.
